package org.lanqiao.myBatis.repository;

import java.util.List;
import org.lanqiao.myBatis.entity.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    List<UserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    int updateByPrimaryKey(UserRole record);
}