package org.lanqiao.myBatis.repository;

import java.util.List;

import org.apache.ibatis.session.RowBounds;
import org.lanqiao.myBatis.dto.UserWithRole;
import org.lanqiao.myBatis.entity.UserProfile;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_profile
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_profile
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_profile
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    UserProfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_profile
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    List<UserProfile> selectAll();
    List<UserWithRole> selectAllWithRoleName();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_profile
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    int updateByPrimaryKey(UserProfile record);

    List<UserProfile> selectAll(RowBounds rowBounds);
    List<UserProfile> selectByExample(UserProfile userProfile);
}