package org.lanqiao.rbac.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commons_user.id
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commons_user.username
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commons_user.password
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commons_user.nick_name
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commons_user.sex
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commons_user.register_date
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commons_user.id
     *
     * @return the value of commons_user.id
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commons_user.id
     *
     * @param id the value for commons_user.id
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commons_user.username
     *
     * @return the value of commons_user.username
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commons_user.username
     *
     * @param username the value for commons_user.username
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commons_user.password
     *
     * @return the value of commons_user.password
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commons_user.password
     *
     * @param password the value for commons_user.password
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commons_user.nick_name
     *
     * @return the value of commons_user.nick_name
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commons_user.nick_name
     *
     * @param nickName the value for commons_user.nick_name
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commons_user.sex
     *
     * @return the value of commons_user.sex
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commons_user.sex
     *
     * @param sex the value for commons_user.sex
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commons_user.register_date
     *
     * @return the value of commons_user.register_date
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commons_user.register_date
     *
     * @param registerDate the value for commons_user.register_date
     *
     * @mbg.generated Fri Aug 18 22:10:32 CST 2017
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}