package org.lanqiao.myBatis.entity;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role.id
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role.name
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role.gmt_create
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role.gmt_modified
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_role.description
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role.id
     *
     * @return the value of rbac_role.id
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role.id
     *
     * @param id the value for rbac_role.id
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role.name
     *
     * @return the value of rbac_role.name
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role.name
     *
     * @param name the value for rbac_role.name
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role.gmt_create
     *
     * @return the value of rbac_role.gmt_create
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role.gmt_create
     *
     * @param gmtCreate the value for rbac_role.gmt_create
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role.gmt_modified
     *
     * @return the value of rbac_role.gmt_modified
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role.gmt_modified
     *
     * @param gmtModified the value for rbac_role.gmt_modified
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_role.description
     *
     * @return the value of rbac_role.description
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_role.description
     *
     * @param description the value for rbac_role.description
     *
     * @mbg.generated Sun Aug 27 11:56:41 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        return "Role{" +
            "id=" + id +
            ", name='" + name + '\'' +
            ", gmtCreate=" + gmtCreate +
            ", gmtModified=" + gmtModified +
            ", description='" + description + '\'' +
            '}';
    }
}